spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otus

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

logging:
  level:
    ru.otus: DEBUG
