spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otus
  #    username: postgres
  #    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show-sql: true
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

logging:
  level:
    ru.otus: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8081
